# -*- coding: utf-8 -*-

AdminUser.create(:email => 'admin@example.com', :password => 'password', :password_confirmation => 'password')

Unidade.create([
	{ nome: 'Niteroi' },
	{ nome: 'Itaperuna' },
	{ nome: 'Macaé' },
	{ nome: 'Volta Redonda' },
	{ nome: 'Nova Friburgo' },
	{ nome: 'Campos dos Goytacazes' },
	{ nome: 'Rio das Ostras' },
	{ nome: 'Santo Antonio de Pádua' },
	{ nome: 'Angra dos Reis' }
])

Ano.create([
	{ ano: 2011, atual: true, pronto: false }	
])

Curso.create([
	{ nome: 'Ciências Econômicas', unidade: Unidade.find_by_nome('Niteroi'), vagas: 161, ano_id: Ano.first },
	{ nome: 'Ciências Sociais - Licenciatura', unidade: Unidade.find_by_nome('Niteroi'), vagas: 51, ano_id: Ano.first },
	{ nome: 'Ciências Sociais - Bacharelado', unidade: Unidade.find_by_nome('Niteroi'), vagas: 31, ano_id: Ano.first },
 	{ nome: 'Direito', unidade: Unidade.find_by_nome('Niteroi'), vagas: 293, ano_id: Ano.first },
	{ nome: 'Geografia - Licenciatura', unidade: Unidade.find_by_nome('Niteroi'), vagas: 54, ano_id: Ano.first },
	{ nome: 'Geografia - Bacharelado', unidade: Unidade.find_by_nome('Niteroi'), vagas: 32, ano_id: Ano.first },
	{ nome: 'História - Licenciatura', unidade: Unidade.find_by_nome('Niteroi'), vagas: 163, ano_id: Ano.first },	
	{ nome: 'Letras - Português/Literaturas - Licenciatura', unidade: Unidade.find_by_nome('Niteroi'), vagas: 74, ano_id: Ano.first },
	{ nome: 'Serviço Social', unidade: Unidade.find_by_nome('Niteroi'), vagas: 176, ano_id: Ano.first },
	{ nome: 'Sociologia', unidade: Unidade.find_by_nome('Niteroi'), vagas: 90, ano_id: Ano.first },	
	{ nome: 'Hotelaria (Tecnólogo em Hotelaria)', unidade: Unidade.find_by_nome('Niteroi'), vagas: 40, ano_id: Ano.first },
	{ nome: 'Administração', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 100 },
	{ nome: 'Antropologia', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 49 },
	{ nome: 'Arquitetura e Urbanismo', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 74  },
	{ nome: 'Arquivologia', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 64 },
	{ nome: 'Artes', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 34 },
	{ nome: 'Biblioteconomia e Documentação', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 64 },
	{ nome: 'Biomedicina', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 49 },
	{ nome: 'Ciência da Computação', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 113 },
	{ nome: 'Ciência Ambiental', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 38 },
	{ nome: 'Ciências Atuariais', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 80 },
	{ nome: 'Ciências Biológicas - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 30 },
	{ nome: 'Ciências Biológicas - Bacharelado', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 66 },
	{ nome: 'Ciências Contábeis', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 100 },
	{ nome: 'Cinema e Audiovisual', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 57 },
	{ nome: 'Comunicação Social - Jornalismo', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 41 },
	{ nome: 'Comunicação Social - Publicidade e Propaganda', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 41 },
	{ nome: 'Desenho Industrial', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 44 },
	{ nome: 'Educação Física - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 50 },
	{ nome: 'Enfermagem', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 90 },
	{ nome: 'Engenharia Agrícola e Ambiental', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Engenharia Civil', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Engenharia de Petróleo', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 36 },
	{ nome: 'Engenharia de Produção', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Engenharia de Recursos Hídricos e do Meio Ambiente', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Engenharia de Telecomunicações', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Engenharia Elétrica', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 68 },
	{ nome: 'Engenharia Mecânica', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Engenharia Química', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 76 },
	{ nome: 'Estatística', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 69 },
	{ nome: 'Estudos de Mídia', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 50 },
	{ nome: 'Farmácia', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 106 },
	{ nome: 'Filosofia - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 46 },
	{ nome: 'Filosofia - Bacharelado', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 44 },
	{ nome: 'Física - Bacharelado', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 40 },
	{ nome: 'Física - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 40 },
	{ nome: 'Física - Licenciatura Noturna', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 48 },
	{ nome: 'Geofísica', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 34 },
	{ nome: 'Letras - Português/Alemão - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 10 },
	{ nome: 'Letras - Bacharelado em Língua e Literatura Alemã', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 6 },
	{ nome: 'Letras - Português/Espanhol - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 35 },
	{ nome: 'Letras - Português/Francês - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 25 },
	{ nome: 'Letras - Bacharelado em Língua e Literatura Francesa', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 10 },
	{ nome: 'Letras - Português/Grego - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 13 },
	{ nome: 'Letras - Bacharelado em Língua e Literatura Grega', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 7 },
	{ nome: 'Letras - Português/Inglês - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 28 },
	{ nome: 'Letras - Português/Italiano - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 14 },
	{ nome: 'Letras - Bacharelado em Língua e Literatura Italiana', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 6 },
	{ nome: 'Letras - Português/Latim - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 20 },
	{ nome: 'Matemática - Licenciatura Noturna', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 59 },
	{ nome: 'Matemática - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 67 },
	{ nome: 'Matemática - Bacharelado', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 24 },
	{ nome: 'Medicina', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 144 },
	{ nome: 'Medicina Veterinária', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 96 },
	{ nome: 'Nutrição', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 66 },
	{ nome: 'Odontologia', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 72 },
	{ nome: 'Pedagogia - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 128 },
	{ nome: 'Produção Cultural', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 58 },
	{ nome: 'Psicologia', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 82 },
	{ nome: 'Química - Licenciatura Noturna', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 26 },
	{ nome: 'Química - Licenciatura', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 21 },
	{ nome: 'Química - Bacharelado', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 17 },
	{ nome: 'Química Industrial', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 38 },
	{ nome: 'Relações Internacionais', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 90 },
	{ nome: 'Sistemas de Informação', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 98 },
	{ nome: 'Turismo', ano_id: Ano.first, unidade: Unidade.find_by_nome('Niteroi'), vagas: 104 },	
	
	{ nome: 'Pedagogia - Licenciatura', unidade: Unidade.find_by_nome('Angra dos Reis'), vagas: 65, ano_id: Ano.first },
	
	{ nome: 'Administração', unidade: Unidade.find_by_nome('Itaperuna'), vagas: 40, ano_id: Ano.first },
	
	{ nome: 'Administração', unidade: Unidade.find_by_nome('Macaé'), vagas: 40, ano_id: Ano.first },
	{ nome: 'Ciências Contábeis', unidade: Unidade.find_by_nome('Macaé'), vagas: 40, ano_id: Ano.first },
	{ nome: 'Direito', unidade: Unidade.find_by_nome('Macaé'), vagas: 112, ano_id: Ano.first },
	
	
	{ nome: 'Administração Pública', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 42, ano_id: Ano.first },
	{ nome: 'Química com ênfase em Química Tecnológica - Bacharelado', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 50, ano_id: Ano.first },
	{ nome: 'Química - Licenciatura', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 50, ano_id: Ano.first },
	{ nome: 'Matemática ênfase em Matemática Computacional - Bacharelado', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 114, ano_id: Ano.first },
	{ nome: 'Administração', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 98, ano_id: Ano.first },
	{ nome: 'Ciências Contábeis', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 98, ano_id: Ano.first },
	{ nome: 'Física ênfase em Física Computacional - Bacharelado', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 114, ano_id: Ano.first },
	{ nome: 'Engenharia de Produção', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 71, ano_id: Ano.first },
	{ nome: 'Engenharia de Agronegócios', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 71, ano_id: Ano.first },
	{ nome: 'Direito', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 66, ano_id: Ano.first },
	{ nome: 'Engenharia Mecânica', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 71, ano_id: Ano.first },
	{ nome: 'Engenharia Metalúrgica', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 71, ano_id: Ano.first },
	{ nome: 'Psicologia', unidade: Unidade.find_by_nome('Volta Redonda'), vagas: 66, ano_id: Ano.first },
	
	{ nome: 'Biomedicina', unidade: Unidade.find_by_nome('Nova Friburgo'), vagas: 24, ano_id: Ano.first },
	{ nome: 'Fonoaudiologia', unidade: Unidade.find_by_nome('Nova Friburgo'), vagas: 28, ano_id: Ano.first },
	{ nome: 'Odontologia', unidade: Unidade.find_by_nome('Nova Friburgo'), vagas: 99, ano_id: Ano.first },
	
	{ nome: 'Ciência da Computação', unidade: Unidade.find_by_nome('Rio das Ostras'), vagas: 56, ano_id: Ano.first },
	{ nome: 'Psicologia', unidade: Unidade.find_by_nome('Rio das Ostras'), vagas: 64, ano_id: Ano.first },
	{ nome: 'Enfermagem', unidade: Unidade.find_by_nome('Rio das Ostras'), vagas: 48, ano_id: Ano.first },
	{ nome: 'Engenharia de Produção', unidade: Unidade.find_by_nome('Rio das Ostras'), vagas: 56, ano_id: Ano.first },
	{ nome: 'Produção Cultural', unidade: Unidade.find_by_nome('Rio das Ostras'), vagas: 56, ano_id: Ano.first },
	{ nome: 'Serviço Social', unidade: Unidade.find_by_nome('Rio das Ostras'), vagas: 56, ano_id: Ano.first },
	
	{ nome: 'Ciências Contábeis', unidade: Unidade.find_by_nome('Miracema'), vagas: 40, ano_id: Ano.first },
	
	{ nome: 'Ciências Econômicas', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 100, ano_id: Ano.first },
	{ nome: 'Ciências Sociais - Bacharelado', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 48, ano_id: Ano.first },
	{ nome: 'Ciências Sociais - Licenciatura', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 52, ano_id: Ano.first },
	{ nome: 'Geografia - Licenciatura', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 65, ano_id: Ano.first },
	{ nome: 'Geografia - Bacharelado', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 35, ano_id: Ano.first },
	{ nome: 'História - Licenciatura', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 49, ano_id: Ano.first },
	{ nome: 'História - Bacharelado', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 51, ano_id: Ano.first },
	{ nome: 'Psicologia', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 100, ano_id: Ano.first },
	{ nome: 'Serviço Social', unidade: Unidade.find_by_nome('Campos dos Goytacazes'), vagas: 96, ano_id: Ano.first },		
	
	{ nome: 'Ciências Naturais - Licenciatura', unidade: Unidade.find_by_nome('Santo Antônio de Pádua'), vagas: 70, ano_id: Ano.first },
	{ nome: 'Física - Licenciatura', unidade: Unidade.find_by_nome('Santo Antônio de Pádua'), vagas: 70, ano_id: Ano.first },
	{ nome: 'Matemática - Licenciatura', unidade: Unidade.find_by_nome('Santo Antônio de Pádua'), vagas: 76, ano_id: Ano.first },
	{ nome: 'Matemática Pura - Bacharelado', unidade: Unidade.find_by_nome('Santo Antônio de Pádua'), vagas: 40, ano_id: Ano.first },
	{ nome: 'Licenciatura em Informática', unidade: Unidade.find_by_nome('Santo Antônio de Pádua'), vagas: 70, ano_id: Ano.first },
	{ nome: 'Pedagogia - Licenciatura', unidade: Unidade.find_by_nome('Santo Antônio de Pádua'), vagas: 108, ano_id: Ano.first }     
])